version: "3.9"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    environment:
      SA_PASSWORD: "168gA#4e&IsU"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
volumes:
  db_data:
